### ISSUE TITLE
When to use utilities instead of duplicating rules?

### ISSUE THREAD

**Issue by davidtheclark** [suitcss/utils#10]
(This is a question of theory and approach rather than a bug, feature request, etc. I thought it would be appropriate to file this as an issue since SUIT is as much about principles and practices as specific tools.)

*Do you have any principles that guide the decision when to use or not use a utility class?* ---- since any rule could be pulled out of a component's rules and implemented as a utility class, while any utility class could be removed and its rules applied directly to components.

When would you build out a pattern using a list of utility classes instead of defining a component class (however minuscule) whose CSS contains the equivalent rules? 

I think a lot of methodological theorizing about scalable CSS comes down to the decision when and whether to construct patterns out of maximally reusable, low-level utilities or distinct, independent components -- reusability or encapsulation, DRYness or simplicity, etc. I'm trying to work out my own thoughts on this to structure the frontend of a large-scale web app; and I was wondering if you, given your experience, have worked out more principles related to this decision than are stated in the docs. (I'm not sure the docs make a very clear statement about when and why to use or not use utilities -- or maybe I missed it.)

Thanks for any thoughts you can offer.

**Comment by simonsmith** [comment]
I think it would be a good idea to get some conventions/guidelines noted down in the docs. I'll close this in favour of https://github.com/suitcss/suit/issues/86 which is a bit more visible and covers similar documentation improvements.
