### ISSUE TITLE
Add pull/push utilities

### ISSUE THREAD

**Issue by necolas** [suitcss/utils#9]
To move things around without altering source order.

**Comment by VinSpee** [comment]
We're toying around with this right now - trying out the syntax

```css
.u-orderFirst
.u-orderLast
```
then maybe adding, as we need them,

```css
.u-order1of12
.u-order2of12
```
etc… thoughts?

**Comment by simonsmith** [comment]
We've got a [utils-flex](https://github.com/simonsmith/utils-flex/) in the works which will handle this

**Comment by VinSpee** [comment]
@simonsmith nice! thanks for the info - looks great.

**Comment by simonsmith** [comment]
utils-flex is now released - https://github.com/suitcss/utils-flex

**Comment by VinSpee** [comment]
Awesome! Thanks!
